image : gqy117/dotnet-2.1.300-sdk-alpine3.7-npm

stages: 
  - build

before_script:
  - 'cd ./scripts; chmod +x -R .'

build:
 stage: build
 script:
  - './1.setup.sh'
  - './2.build.sh'
  - './4.test.sh'
