image : microsoft/dotnet:2.1.300-sdk-alpine3.7

stages: 
  - build

before_script:
  - 'cd ./scripts; chmod +x -R .'

build:
 stage: build
 script:
  - './1.setup.ps1'
  - './2.build.ps1'
  - './4.test.ps1'
