image : microsoft/aspnetcore:2.1.0-preview1-stretch-slim

stages: 
  - build

before_script:
  - 'cd ./scripts; chmod +x -R .'

build:
 stage: build
 script:
  - './1.setup.ps1'
  - './2.build.ps1'
  - './4.test.ps1'
