image : microsoft/aspnetcore-build:2.0.3-stretch

stages: 
  - build
  - test
  - deploy

cache:
  paths:
  - ./src/website/node_modules
  - ~/.nuget
  - ~/.local/share/NuGet/Cache

before_script:
  - 'cd ./scripts; chmod +x -R .'

build:
 stage: build
 script:
  - './1.setup.ps1'
  - './2.build.ps1'

test:
  stage: test
  script:
  - './4.test.ps1'
  artifacts:
    paths:
      - src/website/coverage/
