dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 2.1.300

services:
  - docker

install:
  - nvm install 8.4.0
  - nvm use 8.4.0

before_script:
  - 'cd ./scripts; chmod +x -R .'

script:    
  - './1.setup.ps1'
  - './2.build.ps1'
  - './4.test.ps1'

deploy:
  skip_cleanup: true
  provider: script
  script: './5.docker.ps1'
  on:
    branch: master