image: microsoft/aspnetcore-build:2.0.3-stretch

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
          - node
        script:
          - 'cd ./scripts; chmod +x -R .'
          - './1.setup.ps1'
          - './2.build.ps1'