image: gqy117/dotnet-2.1.300-sdk-alpine3.7-npm

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - 'cd ./scripts; chmod +x -R .'
          - './1.setup.sh'
          - './2.build.sh'
          - './4.test.sh'