image: microsoft/dotnet:2.1.300-sdk-alpine3.7

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - 'cd ./scripts; chmod +x -R .'
          - './1.setup.ps1'
          - './2.build.ps1'
          - './4.test.ps1'