image: microsoft/aspnetcore:2.1.0-preview1-stretch-slim

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - 'cd ./scripts; chmod +x -R .'
          - './1.setup.ps1'
          - './2.build.ps1'
          - './4.test.ps1'