image: microsoft/aspnetcore-build:2.1.300-preview1-stretch

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - 'cd ./scripts; chmod +x -R .'
          - './1.setup.ps1'
          - './2.build.ps1'
          - './4.test.ps1'