image: gqy117/dotnet-2.1.300-sdk-alpine3.7-npm

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - 'cd ./scripts; chmod +x -R .'
          - 'sh ./1.setup.ps1'
          - 'sh ./2.build.ps1'
          - 'sh ./4.test.ps1'