version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-sdk-alpine3.7
    working_directory: ~/repo
    environment:
       SCRIPTS: scripts

    steps:
      - checkout

      - run: chmod +x -R ./$SCRIPTS;
      - run: cd ./$SCRIPTS; ./1.setup.ps1
      - run: cd ./$SCRIPTS; ./2.build.ps1
      - run: cd ./$SCRIPTS; ./4.test.ps1