version: 2
jobs:
  build:
    docker:
      - image: gqy117/dotnet-2.1.300-sdk-alpine3.7-npm
    working_directory: ~/repo
    environment:
       SCRIPTS: scripts

    steps:
      - checkout

      - run: chmod +x -R ./$SCRIPTS;
      - run: cd ./$SCRIPTS; ./1.setup.sh
      - run: cd ./$SCRIPTS; ./2.build.sh
      - run: cd ./$SCRIPTS; ./4.test.sh